services:
  postgres:
    image: postgres:latest
    container_name: postgres-container-alegra
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./data/mongo:/docker-entrypoint-initdb.d
    command: ["mongod"]

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    restart: always

  order-service:
    build: ./services/order_services
    container_name: order-service
    depends_on:
      - kafka
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./services/order_services:/app
      - /app/node_modules
    restart: always
    # command: npm run dev
    # restart: unless-stopped
    command: pm2-runtime start ecosystem.config.js

  kitchen-service:
    build: ./services/kitchen_services
    container_name: kitchen-service
    depends_on:
      - kafka
      - postgres
      - mongodb
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - ./services/kitchen_services:/app
      - /app/node_modules
    # command: npm run dev
    # restart: unless-stopped
    command: pm2-runtime start ecosystem.config.js
  
  market-service:
    build: ./services/market_services
    container_name: market-service
    ports:
      - "3002:3002"
    restart: always
    depends_on:
      - kafka
    volumes:
      - ./services/market_services:/app
      - /app/node_modules
    # command: npm run dev
    # restart: unless-stopped
    command: pm2-runtime start ecosystem.config.js

  inventory-service:
    build: ./services/inventory_services
    container_name: inventory-service
    depends_on:
      - kafka
      - postgres
      - market-service
    ports:
      - "3003:3003"
    restart: always
    volumes:
      - ./services/inventory_services:/app
      - /app/node_modules
    # command: npm run dev
    # restart: unless-stopped
    command: pm2-runtime start ecosystem.config.js
  
  ui-service:
    build: ./services/ui_services
    container_name: ui-service
    depends_on:
      - order-service
      - kitchen-service
      - market-service
      - inventory-service
    ports:
      - "3004:3004"
    restart: always
    volumes:
      - ./services/ui_services:/app
      - /app/node_modules
    # command: npm run dev
    # restart: unless-stopped
    command: pm2-runtime start ecosystem.config.js

volumes:
  postgres_data:
  mongo_data: