# FROM node:18
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# CMD ["npm", "dev"]


FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install -g pm2
RUN npm install

COPY . .

RUN npm run build

CMD ["pm2-runtime", "start", "ecosystem.config.js"]